In [13]:
import numpy as np
import os

from time import time
import datetime

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.preprocessing import OneHotEncoder

import tensorflow
from tensorflow.python.keras.models import Sequential 
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.callbacks import TensorBoard
from tensorflow.python.keras.wrappers.scikit_learn import KerasClassifier
from tensorflow.keras.optimizers import Adam


In [2]:
iris_data = load_iris() # load the iris dataset

In [3]:
print('------------------------------')
print('Example data: \n')
print(iris_data.data[:5])
print('------------------------------')
print('Example labels: \n')
print(iris_data.target[:5])
print('------------------------------')

------------------------------
Example data: 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
------------------------------
Example labels: 

[0 0 0 0 0]
------------------------------


In [4]:
x = iris_data.data

# Convertir los datos a una sola columna
y_ = iris_data.target.reshape(-1, 1)

In [5]:
# Hacemos 'One Hot encode' para las labels

encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
#print(y)

In [6]:
# Estandarizamos los datos

x_standard = preprocessing.scale(x)

In [7]:
# Dividimos entre train y test

train_x, test_x, train_y, test_y = train_test_split(x_standard, y, test_size=0.20)

In [8]:
# construimos el modelo

model = tensorflow.keras.Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

In [9]:
# Optimizador Adam con learning rate de 0.001

optimizer = Adam(lr=0.001)

# Compilamos e imprimimos un resumen del modelo 

model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

Neural Network Model Summary: 
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 10)                110       
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
# Cargamos la extension del notebook TensorBoard 
%load_ext tensorboard

In [14]:
# Instanciamos un objeto de clase Tensoboard para usar en el parametro callback

log_dir= os.path.join('logs','fit','') + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard = tensorflow.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Entrenamos el modelo

model.fit(train_x, train_y, verbose=0, batch_size=5, epochs=50, validation_data=(test_x, test_y),
    callbacks=[tensorboard])

In [16]:
# Testamos los resultados sobre datos no utilizados para entrenar el modelo

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

30/30 [==============================] - 0s 4ms/sample - loss: 0.0531 - accuracy: 1.0000
Final test set loss: 0.053135
Final test set accuracy: 1.000000


In [18]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 32392), started 0:01:09 ago. (Use '!kill 32392' to kill it.)